<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="68978" started-at="2017-12-09T08:25:53Z" finished-at="2017-12-09T08:27:02Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="68978" started-at="2017-12-09T08:25:53Z" finished-at="2017-12-09T08:27:02Z">
      <class name="scripts.TestValidLogin">
        <test-method status="PASS" signature="openApplications()[pri:0, instance:scripts.TestValidLogin@42e26948]" name="openApplications" is-config="true" duration-ms="32933" started-at="2017-12-09T13:55:53Z" finished-at="2017-12-09T13:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplications -->
        <test-method status="FAIL" signature="validLogin()[pri:0, instance:scripts.TestValidLogin@42e26948]" name="validLogin" duration-ms="6014" started-at="2017-12-09T13:56:26Z" finished-at="2017-12-09T13:56:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [actiTIME - Enter Time-Track] but found [actiTIME - Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [actiTIME - Enter Time-Track] but found [actiTIME - Login]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at scripts.TestValidLogin.validLogin(TestValidLogin.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:scripts.TestValidLogin@42e26948]" name="closeApplication" is-config="true" duration-ms="300" started-at="2017-12-09T13:56:32Z" finished-at="2017-12-09T13:56:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- scripts.TestValidLogin -->
      <class name="scripts.TestInvalidLogin">
        <test-method status="PASS" signature="openApplications()[pri:0, instance:scripts.TestInvalidLogin@57baeedf]" name="openApplications" is-config="true" duration-ms="16540" started-at="2017-12-09T13:56:33Z" finished-at="2017-12-09T13:56:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplications -->
        <test-method status="PASS" signature="testInvalidLogin()[pri:0, instance:scripts.TestInvalidLogin@57baeedf]" name="testInvalidLogin" duration-ms="12635" started-at="2017-12-09T13:56:49Z" finished-at="2017-12-09T13:57:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:scripts.TestInvalidLogin@57baeedf]" name="closeApplication" is-config="true" duration-ms="161" started-at="2017-12-09T13:57:02Z" finished-at="2017-12-09T13:57:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- scripts.TestInvalidLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
